### 아인슈타인 합
* bellman equation의 $P^{\pi}$를 연산할때 활용
## $$P^{\pi}_{ss'} = \sum_{a \in \cal{A}} \pi(a|s) P_{ss'}^a $$

* `아인슈타인 합` 대부분의 텐서연산 라이브러리에서 __똑같은 문법으로__ 사용할수 있게 구현되어있음.
* `numpy`에서 아인슈타인 합으로 표현한 수식은 `pytorch`에서도 동일하게 사용할 수 있다.
* `아인슈타인 합`은 Tensorflow/Pytorch에서 모델을 개발할때 매우 최적화된 방법. 

참조 : [EINSUM IS ALL YOU NEED - 2018](https://rockt.github.io/2018/04/30/einsum)

### 아인슈타인 합의 장점

Einsum 표기법은 본질적으로 도메인 특정 언어를 사용하여 텐서에 대한 복잡한 작업은 물론 이러한 모든 것을 표현하는 우아한 방법입니다. 
이것은 특정 라이브러리 기능을 암기하거나 정기적으로 검색할 필요가 없다는 것 이상의 이점이 있습니다. 
einsum을 이해하고 활용하면 더 간결하고 효율적인 코드를 더 빨리 작성할 수 있습니다. 
einsum을 사용하지 않을 때 생략할 수 있는 중간 텐서뿐만 아니라 텐서의 불필요한 재구성 및 전치도 도입하기 쉽습니다. 
또한 einsum과 같은 도메인 특정 언어는 때때로 고성능 코드로 컴파일될 수 있으며 einsum과 같은 도메인 특정 언어는 실제로 GPU 코드를 자동으로 생성하고 특정 입력 크기에 대한 코드. 또한 opt einsum 및 tf einsum opt와 같은 프로젝트를 사용하여 einsum 식의 텐서 축소 순서를 최적화할 수 있습니다.

### Matrix Transpose
## $B_{ji} = A_{ij}$ 

In [17]:
# Matrix Transpose
import torch
a_ij = torch.arange(6).reshape(2,3)
print('a_ij',a_ij )
b_ji = torch.einsum('ij->ji',[a])
print('b_ji',b_ji)

a_ij tensor([[0, 1, 2],
        [3, 4, 5]])
b_ji tensor([[0, 3],
        [1, 4],
        [2, 5]])


### Sum
## $b = \sum_{i}\sum_{j}A_{ij}$

In [2]:
# Sum
print('a',a )
torch.einsum('ij->', [a]) # 2x3 -> 스칼라 (전체 합)

a tensor([[0, 1, 2],
        [3, 4, 5]])


tensor(15)

### COLUMN SUM
## $b_j =\sum_iA_{ij}$ 

In [4]:
# Column Sum
print('a',a )
torch.einsum('ij->j', [a]) # 2x3 행렬 -> (1x)3 벡터 

a tensor([[0, 1, 2],
        [3, 4, 5]])


tensor([3, 5, 7])

### Row SUM
## $b_i =\sum_jA_{ij}$ 

In [5]:
# Row Sum
print('a',a)
torch.einsum('ij->i',[a]) # 2x3 -> 2 벡터

a tensor([[0, 1, 2],
        [3, 4, 5]])


tensor([ 3, 12])

### Matrix-Vector Multiplication
## $c_i = \sum_kA_{ik}b_k $

In [15]:
# Matrix-vector multiplication
a = torch.arange(6).reshape(2,3)
b = torch.arange(3)
print('a',a) # 2 x 3
print('b',b) # 3 vector
torch.einsum('ik,k->i', [a,b]) # (2,3)x(3,1) -> (2,1) 

a tensor([[0, 1, 2],
        [3, 4, 5]])
b tensor([0, 1, 2])
tensor([[ 0,  1,  4],
        [ 0,  4, 10]])


### Matrix-Matrix Multiplication
## $c_{ij} = \sum_kA_{ik}B_{kj} $

In [18]:
# Matrix-Matrix multiplication
a = torch.arange(6).reshape(2,3)
b = torch.arange(15).reshape(3,5)
print('a',a) # 2 x 3
print('b',b) # 3 x 5
torch.einsum('ik,kj->ij', [a,b]) # (2,3)x(3,5) -> (2,5) 

a tensor([[0, 1, 2],
        [3, 4, 5]])
b tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])


tensor([[ 25,  28,  31,  34,  37],
        [ 70,  82,  94, 106, 118]])

### Dot Product
## $c = \sum_ia_ib_i$

In [21]:
a = torch.arange(3)
b = torch.arange(3,6)
print('a',a)
print('b',b)
torch.einsum('i,i->',[a,b])

a tensor([0, 1, 2])
b tensor([3, 4, 5])


tensor(14)

### Hadamard Product 
## $C_{ij}=A_{ij}B_{ij}$

In [22]:
a = torch.arange(6).reshape(2,3)
b = torch.arange(6,12).reshape(2,3)
print('a',a)
print('b',b)
torch.einsum('ij,ij->ij',[a,b])

a tensor([[0, 1, 2],
        [3, 4, 5]])
b tensor([[ 6,  7,  8],
        [ 9, 10, 11]])


tensor([[ 0,  7, 16],
        [27, 40, 55]])

### Outer Product
## $C_ij = a_ib_j$

In [23]:
a = torch.arange(6)
b = torch.arange(3,6)
print('a',a)
print('b',b)
torch.einsum('i,j->ij',[a,b])

a tensor([0, 1, 2, 3, 4, 5])
b tensor([3, 4, 5])


tensor([[ 0,  0,  0],
        [ 3,  4,  5],
        [ 6,  8, 10],
        [ 9, 12, 15],
        [12, 16, 20],
        [15, 20, 25]])

### Batch Matrix Multiplication
## $C_{ijl} = \sum_kA_{ijk}B_{ikl}$

In [31]:
a = torch.randn(3,2,5)
b = torch.randn(3,5,3)
print('a',a)
print('b',b)
torch.einsum('ijk,ikl->ijl', [a, b])

a tensor([[[-1.1483,  0.5665, -2.6095,  1.1390,  0.6329],
         [-1.5654,  0.0299, -1.3396, -1.7746,  0.0240]],

        [[ 0.3892, -0.8946,  0.3252, -0.2125, -0.3353],
         [ 1.2297, -1.0666,  0.0738, -0.0228,  0.2932]],

        [[-0.3741,  0.3963, -0.2513, -1.1525,  0.2359],
         [-0.0113, -0.5739, -0.4826,  0.8517, -0.0372]]])
b tensor([[[ 1.3296, -0.2150, -0.2713],
         [-1.2721, -0.3941, -0.9409],
         [-0.1849,  0.6673, -0.5381],
         [ 0.3546,  1.5982,  0.0145],
         [ 0.6154,  0.5576,  0.8346]],

        [[-0.8808,  0.1802,  0.5557],
         [ 0.0053, -0.0421,  1.1783],
         [ 0.9310,  0.5647, -2.0817],
         [-0.4445, -0.2962,  0.4346],
         [-0.0397,  0.6988, -0.5897]],

        [[ 0.7605, -1.4042, -0.4048],
         [ 0.4555, -1.0740,  1.2074],
         [-1.1109, -0.8025, -1.1154],
         [-0.9516, -0.9417, -0.7870],
         [ 0.1363, -1.4885,  0.1499]]])


tensor([[[-0.9716,  0.4556,  1.7274],
         [-2.4861, -3.3920,  1.1118]],

        [[ 0.0629,  0.1200, -1.4093],
         [-1.0216,  0.5197, -0.9099]],

        [[ 1.3039,  1.0354,  1.8525],
         [-0.5495,  0.2729, -0.8260]]])

### Tensor contraction
## $C_{pstuv} = \sum_q\sum_rA_{pqrs}B_{tuqvr}$



In [36]:
a = torch.randn(2,3,5,7)
b = torch.randn(11,13,3,17,5)
print('a',a.shape)
print('b',b.shape)
torch.einsum('pqrs,tuqvr->pstuv', [a, b]).shape

a torch.Size([2, 3, 5, 7])
b torch.Size([11, 13, 3, 17, 5])


torch.Size([2, 7, 11, 13, 17])

### Bilinear transformation
## $D_{ij} = \sum_k\sum_lA_{ik}B_{jkl}C_{il}$