## 강의 내용
>행렬 및 벡터 표현법 
>기본 숫자 데이터 정확도

* 컴퓨터로 숫자를 다룰 때는 오차가 발생 : 소수점 표현에 한계가 있음

* double precision : float64. numpy에서 기본 값으로 사용
    * 허수, 실수 각각 64이므로 complex 128이라고도 함
    * normalized floating-point로 표현가능하다.
        * $0.1453..x10^-{15}$
        * $0.1453..E-15$
        * 소수점 16자리까지 표현 가능
        * $10^{-308}~10^308$

* numpy.array : 2D array로 행렬, 1D array로 벡터 표현

* 행렬 및 벡터의 사이즈 확인 : shape

* complex 행렬 및 complex 벡터 표현 : 허수를 포함
    * 허수를 표현할 때 무조건 숫자가 앞에 있어야함. 1이더라도

* 행렬과 벡터 값 접근
    * 인덱스 값이 0부터 시작한다.
    * i행 j열의 엔트리
        * a$[i,j]$
        * a$[i][j]$
    * 허수의 경우 
        * 0으로 바꿀경우 0j로 만듬.
        * a = np.array($[]$,dtype = np.float64)
        * np.float64가 default 값 : 허수를 넣지 못함
        * 처음부터 np.complex128 을 넣어주면 : 허수를 넣을 수 있다.
        * 행렬에 하나라도 허수를 넣은채 생성하면 complex128로 생성됨
    
* 명시적 타입 변환
    * .astype() : 엔트리들의 타입을 변환

* 암묵적 타입 변환
    * a가 float이고 b가 complex일때 a+b,a*c = complex로 자동 변환됨
    * 정확한 타입의 변환을 알지 못한다면 사용하지 않는 것을 추천
    


### 코드

In [1]:
import numpy as np

In [3]:
a = np.array([[1,2.5,3],[-1,-2,-1.5],[4,5.5,6]])

In [4]:
# 2D array
a

array([[ 1. ,  2.5,  3. ],
       [-1. , -2. , -1.5],
       [ 4. ,  5.5,  6. ]])

In [6]:
# 1D array
b = np.array([7.0,5.0,3.0])
b

array([7., 5., 3.])

In [7]:
# shape , tuple 자료형으로 출력 (행,열)
print(a.shape)
print(b.shape)


(3, 3)
(3,)


In [20]:
# complex 행렬 및 벡터 표현
a = np.array([[1-2j,3+1j,1],[1+2j,2-1j,7]])
a

array([[1.-2.j, 3.+1.j, 1.+0.j],
       [1.+2.j, 2.-1.j, 7.+0.j]])

In [18]:
b = np.array([1+8j,-2j])
b

array([ 1.+8.j, -0.-2.j])

In [19]:
a.shape,b.shape

((2, 3), (2,))

In [23]:
b

array([ 1.+8.j, -0.-2.j])

In [22]:
a

array([[1.-2.j, 3.+1.j, 1.+0.j],
       [1.+2.j, 2.-1.j, 7.+0.j]])

In [25]:
a[1,1]=0
a[0,2]=0
b[0]=0

In [26]:
# np.complex128
a

array([[1.-2.j, 3.+1.j, 0.+0.j],
       [1.+2.j, 0.+0.j, 7.+0.j]])

In [28]:
type(a[0,0])

numpy.complex128

In [27]:
# np.complex128
b

array([ 0.+0.j, -0.-2.j])

In [29]:
# 엔트리들의 타입을 변환할 수 있음 : 허수 -> 실수 : 허수부분날라감
a= a.astype(dtype=np.float64)
a

<ipython-input-29-dcae06f968d8>:2: ComplexWarning: Casting complex values to real discards the imaginary part
  a= a.astype(dtype=np.float64)


array([[1., 3., 0.],
       [1., 0., 7.]])

### 연습문제1 

In [32]:
a = np.array([[1,2,4,1],[2,1,3,1],[5,2,1,4]])

In [34]:
a

array([[1, 2, 4, 1],
       [2, 1, 3, 1],
       [5, 2, 1, 4]])

In [35]:
a.shape

(3, 4)

In [41]:
a = a.astype(np.complex128)

In [42]:
a[0,2] = 1+2j
a[2,1] = 1+2j
a

array([[1.+0.j, 2.+0.j, 1.+2.j, 1.+0.j],
       [2.+0.j, 1.+0.j, 3.+0.j, 1.+0.j],
       [5.+0.j, 1.+2.j, 1.+0.j, 4.+0.j]])

In [44]:
a[0,2] = 0 
a[2,1] = 0
a

array([[1.+0.j, 2.+0.j, 0.+0.j, 1.+0.j],
       [2.+0.j, 1.+0.j, 3.+0.j, 1.+0.j],
       [5.+0.j, 0.+0.j, 1.+0.j, 4.+0.j]])