### 학습 내용
> 행렬 관련 편리한 기능

* np.eye : band에 1채워 넣기
    * np.eye(row,col,k=band_id,dtype=선택)
    * default : col개수 미입력시 square로 생성, band_id = 0
    * band = 0일때 diagonal

* np.identity : identity matrix 생성
    * np.identity(n,dtype=선택) : n by n Identity matrix생성

* np.tri
    * lower triangular matrix
    * nonzero entry = 1
    * k $\leq$ band_id의 모든 밴드에 1, 나머지는 0
    
* np.zero : 0으로 채우기

* np.ones : 1로 채우기

* np.full : 원하는 값으로 채우기

* np.random.rand : Random 값(0-1사이)으로 채워넣기 



### code

In [2]:
import numpy as np

In [3]:
# np.eye
a = np.eye(3,3,k=0)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
# np.identity
b = np.identity(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
# np.tri
c = np.tri(2,3,k=1)
c

array([[1., 1., 0.],
       [1., 1., 1.]])

In [9]:
c = np.tri(3,3,k=0)
c

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [10]:
#zero/one/full
a = np.zeros((3,3))
b = np.ones((3,3))
c = np.full((3,3),5)
a,b,c

(array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]),
 array([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]]))

In [11]:
# Random
a = np.random.rand(3,3)
a

array([[0.1669748 , 0.4589209 , 0.67648663],
       [0.09398995, 0.30046474, 0.59994094],
       [0.86142146, 0.21203305, 0.94716675]])

In [18]:
# 연습
a = np.identity(20,dtype = np.float64)
a

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.

In [19]:
# 연습
a = np.random.rand(3,3)
a.astype(np.complex128)

array([[0.42265422+0.j, 0.11847821+0.j, 0.39245203+0.j],
       [0.43860925+0.j, 0.69276653+0.j, 0.31351201+0.j],
       [0.79957485+0.j, 0.05698041+0.j, 0.09200681+0.j]])