### 학습 내용
> 행렬 기본 조작(1)

* np.copy 
    * 원본 데이터를 복사해서 독립적으로 활용하고 싶을때 
    * 서로 다른 메모리(공간)사용

* np.reshape(matrix, 숫자 혹은 shape(튜플))
    * shape를 바꾸기 위해 사용
    * 바꾸기 전 데이터와 같은 메모리 공간 사용
    * 독립적으로 사용하기 위해서는 np.copy(np.reshape)

* np.tril
    * band_id 포함 lower부분만 copy,나머지 0
    * 독립적 사용 가능

* np.triu
    * band_id 포함 upper부분만 copy,나머지 0
    * 독립적 사용 가능
    
* np.diag 
    * band 뽑아 내어 1D array로 만듬
    * 같은 메모리 공간 사용(종속적)
        * diag는 수정 불가 : read-only
    * 입력이 1D array(벡터)이면 square행렬 생성
        * 해당 밴드에 1D벡터를 삽입, 나머지 0

* np.diagflat(M,k=band_id)
    * M을 1D로 만든뒤 band에 삽입해서 square matrix생성 

* np.trace(matrix,offset=band_id)
    * 해당 band entry들을 모두 더한 값을 출력
    * diagonal의 합을 구할수 있다

* flatten() / np.ravel
    * 행렬을 1D화 
    * flatten : 독립적으로 사용가능
    * ravel : 종속적, 같은 메모리 공간 참조
    

### code

In [2]:
import numpy as np

In [3]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
b = np.tril(a,0)
b

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [6]:
# upper triangle
c = np.triu(a,0)
c

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [9]:
# lower triangle
d = np.tril(a,-1)
d

array([[0, 0, 0],
       [4, 0, 0],
       [7, 8, 0]])

In [11]:
# diagonal 추출 
diag = np.diag(a,0)
a, diag

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([1, 5, 9]))

In [14]:
# diagonal을 갖는 행렬 생성
diag_2 = np.diag(diag,0)
diag,diag_2

(array([1, 5, 9]),
 array([[1, 0, 0],
        [0, 5, 0],
        [0, 0, 9]]))

In [15]:
a = np.random.rand(2,3)

In [19]:
# 행렬을 1D로 만든뒤 band에 삽입
b = np.diagflat(a,0)
a,b,a.shape,b.shape

(array([[0.86733299, 0.62287377, 0.83787757],
        [0.68327712, 0.4603379 , 0.26006842]]),
 array([[0.86733299, 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [0.        , 0.62287377, 0.        , 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.83787757, 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , 0.68327712, 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.4603379 ,
         0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.26006842]]),
 (2, 3),
 (6, 6))

In [23]:
# diagonal의 합
a = np.ones((4,4))
b = np.trace(a)
a,b

(array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 4.0)

In [25]:
# 행렬을 1D화 
a.flatten() ,a.ravel()

(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]))

In [28]:
# 연습문제 
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
b = a.reshape(5,3)
bt = np.triu(b,0)
d = np.diagflat(bt,0)
t = np.trace(d,0)
a,b,bt,d,t


(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]),
 array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]]),
 array([[1, 2, 3],
        [0, 5, 6],
        [0, 0, 9],
        [0, 0, 0],
        [0, 0, 0]]),
 array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 