### 학습 내용
> 행렬 기본 조작(2)

* np.hstack /np.vstack
    * 2D array (행렬을 인자로 받을 때)
        * hstack : 가로로 쌓음
        * vstack : 세로로 쌓음
    * 1D array (벡터를 인자로 받을 때)
        * hstack : 더 길어진 1D array(벡터)
        * vstack : 수직으로 쌓아 2D array(행렬)생성 

* transpose
    * a.transpose
    * a.T
    * 같은 메모리 공간 참조 : copy사용해서 독립적으로 사용가능
    * **1D array에 적용하면 transpose되지 않음.사용 x** 

* real property / img property / conjugate method
    * .real :실수
    * .imag :허수의 계수
    * .conjugate() : 켤레 복소수

* scalar multiplication
    * r(sclar) * A
        
* matrix multiplication
    * np.matmul(A,B) 
    * A@B 
    * matrix - vector 연산도 가능

* inner product 
    * np.vdot(u,v)
        * 실수 :$u \centerdot v =u_1v_1+u_2v_2+...+u_nv_n$
        * complex의 경우 : conjugate를 앞에 먹임
            * 인자의 순서를 반대로 해야 정상적인 결과를 얻을 수 있다.
    * np.dot(u,v)
        * 실수 : vdot과 동일
        * complex : conjugate이 빠진 채로 계산. inner product가 아님

* Norm
    * from scipy import linalg
    * norm = linalg.norm(a,n)
        * $l_1-vector norm$ : 절대값 , n=1
        * $l_2-vector norm$ : 제곱의 루트 , n=2
        * $l_\infty-vector norm$ : 최대값의 절대값 , n=inf
        * $l_1-matrix norm$ : 절대값의 최대값 , n=1
        * $l_2-matrix norm$ : 절대값의 제곱의 루트 , n=2
        * $l_\infty-matrix norm$ : 최대값의 절대값 , n=inf
    
* 행렬 슬라이싱
    * 행렬에서 원하는 부분만 뽑아내기 : 인덱스 사용
    * 0부터 시작
    
    


### code

In [1]:
import numpy as np

In [4]:
# 인자가 2D array일때 hstack,vstack
a = np.array([[1,2,3],[3,4,5]])
b = np.array([[4,5,6],[7,8,9]])
new_mat = np.hstack((a,b))
print(new_mat)
new_mat = np.vstack((a,b))
print(new_mat)

[[1 2 3 4 5 6]
 [3 4 5 7 8 9]]
[[1 2 3]
 [3 4 5]
 [4 5 6]
 [7 8 9]]


In [5]:
# 인자가 1D array일때 hstack,vstack
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
new_mat = np.hstack((a,b,c))
print(new_mat)
new_mat = np.vstack((a,b,c))
print(new_mat)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
# transpose,T
a = np.array([[1,2,3]])
a = np.diagflat(a,2)
print(a)
print(a.T)
print(a.transpose())

[[0 0 1 0 0]
 [0 0 0 2 0]
 [0 0 0 0 3]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]]


In [17]:
# real,imag,conjugate
a = np.array([[1-1j,2,3+1j],[1+2j,0,7+2j]],dtype = np.complex128)
print(a)
print("실수",a.real)
print("허수",a.imag)
print("복소수",a.conjugate())

[[1.-1.j 2.+0.j 3.+1.j]
 [1.+2.j 0.+0.j 7.+2.j]]
실수 [[1. 2. 3.]
 [1. 0. 7.]]
허수 [[-1.  0.  1.]
 [ 2.  0.  2.]]
복소수 [[1.+1.j 2.-0.j 3.-1.j]
 [1.-2.j 0.-0.j 7.-2.j]]


In [20]:
# scalar multiplication
a, a * 6 ,6*a

(array([[1.-1.j, 2.+0.j, 3.+1.j],
        [1.+2.j, 0.+0.j, 7.+2.j]]),
 array([[ 6. -6.j, 12. +0.j, 18. +6.j],
        [ 6.+12.j,  0. +0.j, 42.+12.j]]),
 array([[ 6. -6.j, 12. +0.j, 18. +6.j],
        [ 6.+12.j,  0. +0.j, 42.+12.j]]))

In [23]:
# matrix multiplicaiton
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,0],[2,1],[3,2]])
a,b,a @ b,np.matmul(a,b)

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 0],
        [2, 1],
        [3, 2]]),
 array([[14,  8],
        [32, 17]]),
 array([[14,  8],
        [32, 17]]))

In [24]:
# norm
from scipy import linalg

In [28]:
# L1,L2
a,linalg.norm(a,1),linalg.norm(a,2)

(array([[1, 2, 3],
        [4, 5, 6]]),
 9.0,
 9.508032000695723)

In [29]:
# 행렬 슬라이싱
A = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[-1,-2,-3,-4,-5]])
b = A[1:3,1:4]
c = A[:,:2]
A,b,c

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [-1, -2, -3, -4, -5]]),
 array([[ 7,  8,  9],
        [12, 13, 14]]),
 array([[ 1,  2],
        [ 6,  7],
        [11, 12],
        [-1, -2]]))

In [31]:
# 연습
A = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[-1,-2,-3,-4,-5]])
v1 = A[:,1]
v2 = A[:,2]
v3 = A[:,3]
B = np.vstack((v1,v2,v3))
A,v1,v2,v3,B

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [-1, -2, -3, -4, -5]]),
 array([ 2,  7, 12, -2]),
 array([ 3,  8, 13, -3]),
 array([ 4,  9, 14, -4]),
 array([[ 2,  7, 12, -2],
        [ 3,  8, 13, -3],
        [ 4,  9, 14, -4]]))

In [32]:
B @ v1

array([201, 224, 247])

In [50]:
A = np.array([[1,2],[3,4]])
x = np.array([[5],[6]])
A,x, x.T@A@x

(array([[1, 2],
        [3, 4]]),
 array([[5],
        [6]]),
 array([[319]]))

In [49]:
np.reshape(x,(1,2))

array([[5, 6]])