### 학습 내용
> 행렬 기본 조작(3)

* 같은 사이즈의 행렬 / 벡터 덧셈 뺄셈
    * 같은 사이즈의 경우에만 가능  
        * 덧셈 : $A + B$
        * 뺄셈 : $A - B$

* 스칼라(r)와 행렬의 덧셈
    * $r + A = A + r$ : 모든 엔트리에 스칼라를 더해줌

* matrix multiplication : A@B, np.matmul(A,B)

* A * B : 같은 위치의 엔트리 끼리 곱해서 결과를 반환.
    * matrix multiplication과 다름 

* A / B : 같은 위치의 엔트리 끼리 나눔

* 행렬의 행,열을 내 마음대로 뽑아서 행렬로 만들기
    * idx = $[2,1]$
    * what_i_want = $A[idx,:]$
    * what_i_want = $A[:,idx]$
    * what_i_want =$A[idx_r,:][:,idx_c]$

### code

In [1]:
import numpy as np

In [5]:
# ex
A = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[-1,-2,-3,-4,-5]])
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [-1, -2, -3, -4, -5]])

In [6]:
idx = [1,2]
A[:,idx]

array([[ 2,  3],
       [ 7,  8],
       [12, 13],
       [-2, -3]])

In [7]:
idx = [1,2]
A[idx,:]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [8]:
idx_r = [1,2]
idx_c = [1,2]
A[idx,:][:,idx]

array([[ 7,  8],
       [12, 13]])