### 학습 내용
>행렬 방정식

>일반행렬

* Scipy linalg 사용
    * 호출 : from scipy import linalg

* determinant 구하기 : linalg.det(A)
    * 기본 알고리즘 : LU decomposition
        * $A = LU$
        * $det(A) = det(L*U)= det(L)*det(U) = det(U)$
    * Lapack 함수(subroutine)
        * zgetrf : complex128
        * dgetrf : float64

* 역행렬 구하기(명시적) : linalg.inv(A)
    * 기본 알고리즘 : LU decomposition
        * solve $LUA^{-1} = I$
    * Lapack 함수
        * getrf : LU decomposition
        * getri : inverse from triangular matrix

* Ax = b 풀기 : linalg.solve(A,b,assume_a="gen")
    * assume_a : 행렬의 특성
        * gen : general , default
            * 기본 알고리즘 : LU decomposition
            * Lapack : gesv
        * sym : symmetric ($A=A^T$)
            * 기본 알고리즘 : diagonal pivoting
            * Lapack : sysv
        * her : hermitian ($A=A^*$)
            * 기본 알고리즘 : diagonal pivoting
            * Lapack : hesv
        * pos : positive definite (Quadratic form : $x^TAx > 0$)
            * 기본 알고리즘 : Cholesky decomposition
            * Lapack : posv
        * 설정을 잘못넣어도 별다른 에러가 나오지 않을 수 있으니 주의해야함
        * 잘 모르는 경우 "gen"을 사용할 것
    * A@x - b 가 0에 가까울수록 정확

* Triangular matrix solver : linalg.solve_triangular(A,b,lower = False)
    * triangular matrix 일때 더 효율적으로 해를 찾음
        * lower = False : upper triangular matrix가 default
    * Lapack 
        * trtrs

* 구한 해의 정확성 체크 : np.allclose(A@x,b)
    * 수치적 계산으로 근사된 값의 정확성 체크
        * True(정확) / False 로 반환
    * np.allclose(A@x,b)
        * A@x ,b 비교
    * np.allclose(A@x,np.zeros((b.shape[$0$],)))
        * A@x - b , 0 비교


    

### code

In [1]:
from scipy import linalg
import numpy as np 

In [3]:
# linalg.det
a = np.array([[1,5,0],[2,4,-1],[0,-2,0]])
b = np.array([[1,-4,2],[-2,8,-9],[-1,7,0]])
print(linalg.det(a), linalg.det(b))

-2.0 15.0


In [10]:
# linalg.inv
A = np.array([[1,2,1],[2,1,3],[1,3,1]])
print(linalg.inv(A))

[[ 8. -1. -5.]
 [-1.  0.  1.]
 [-5.  1.  3.]]


In [16]:
# linalg.solve(A,b,assume_a="gen")
b = np.ones((3,1))
gen_A = np.array([[0,1,2],[1,0,3],[4,-3,8]])
sym_A = np.array([[1,2,1],[2,1,3],[1,3,1]])
cpxsym_A = np.array([[1,2-1j,1+2j],[2-1j,1,3],[1+2j,3,1]])
her_A = np.array([[1,2+1j,1-2j],[2-1j,1,3],[1+2j,3,1]])
pos_A = np.array([[2,-1,0],[-1,2,-1],[0,-1,2]])
singular_A = np.array([[1,3,4],[-4,2,-6],[-3,-2,-7]])

In [18]:
print(
    linalg.solve(gen_A,b,assume_a="gen")
    ,linalg.solve(sym_A,b,assume_a="sym")
    ,linalg.solve(cpxsym_A,b,assume_a="sym")
    ,linalg.solve(her_A,b,assume_a="her")
    ,linalg.solve(pos_A,b,assume_a="pos")
)

[[ 1.]
 [ 1.]
 [-0.]] [[ 2.]
 [ 0.]
 [-1.]] [[0.00689655+0.11724138j]
 [0.35172414-0.02068966j]
 [0.17241379-0.06896552j]] [[0.11111111+1.11111111e-01j]
 [0.33333333-1.11111111e-01j]
 [0.11111111+1.11022302e-16j]] [[1.5]
 [2. ]
 [1.5]]


In [20]:
# linalg.solve_triangular(A,b,lower=True)
A = np.array([[1,0,0,0],[1,4,0,0],[5,0,1,0],[8,1,-2,2]])
b = np.array([1,2,3,4])
x = linalg.solve_triangular(A,b,lower=True)
A,b,x

(array([[ 1,  0,  0,  0],
        [ 1,  4,  0,  0],
        [ 5,  0,  1,  0],
        [ 8,  1, -2,  2]]),
 array([1, 2, 3, 4]),
 array([ 1.   ,  0.25 , -2.   , -4.125]))

In [26]:
# np.allclose(A@x,b)
b = np.ones((3,1))
x = linalg.solve(pos_A,b,assume_a="pos")
bool_close = np.allclose(pos_A@x,b)

In [29]:
pos_A@x,b,bool_close

(array([[1.],
        [1.],
        [1.]]),
 array([[1.],
        [1.],
        [1.]]),
 True)

In [30]:
# 연습문제 