### 학습 내용
>행렬 방정식
>밴드행렬

* SciPy에서의 밴드 행렬 입력 
    * 열 index를 유지하면서 밴드만 가져와서 가로 형태로 쌓아줌 

* 밴드 행렬 Solver : linalg.solve_banded((lbw,ubw),band_a,b)
    * lbw : lower band width
    * ubw : upper band width
    * 기본 알고리즘
        * LU decomposition
        * tridiagonal solver
    * Lapack
        * gbsv
        * gtsv

* Positive definite band matrix solver : linalg.solveh_banded
    

### code

In [1]:
from scipy import linalg
import numpy as np 

In [8]:
# linalg.solve_banded((lbw,ubw),band_a,b)
A = np.array([[1,2,0,0],[0,1,1,0],[0,0,1,2],[0,0,0,1]])
print(A) # upper band width = 1
b = np.ones((4,1))
print(b)
linalg.solve_banded((1),A,b)

[[1 2 0 0]
 [0 1 1 0]
 [0 0 1 2]
 [0 0 0 1]]
[[1.]
 [1.]
 [1.]
 [1.]]


TypeError: cannot unpack non-iterable int object