### 학습 내용
>행렬 분해

>LU decomposition

* LU Decomposition : P,L,U = linalg.lu(A)
    * A = LU , A=PLU
    * L : lower triangular, U : upper trianglular
    * P : pivoting한 결과를 담은 permutation 행렬
        * Pivoting : 때에 따라 decomposition 중에 필요시 row interchange 진행
    * P,L,U를 구해보고 싶을때
    
* LU Decomposition for Solver : lu,piv = linalg.lu_factor(A)
    * Ax = b를 풀기 위한 방법
    * lu : L,U를 한 행렬에 저장
        * L의 diagonal entry=1인것을 알기 때문에 U와 L을 한 행렬에 저장 가능
    * piv : permutation(row interchange)정보를 담고 있는 1D array
        * permutation vector (perm)을 구할 수 있다.
        * P = np.identity(4)$[perm,:]$
        * A = P@L@U = (L@U)$[perm,:]$
        
* LU Decomposition Solver : linalg.lu_solve((lu,piv),b)
    * linalg.lu_factor를 통해 구한 lu,piv를 인자로 사용
        * piv를 perm으로 바꿀 필요 없음
    * Ax=b의 형태에서 b를 바꿔가면서 해를 구해야 할때 유용
    * Lapack
        * gettrf $\to$ gettrs

* LU Decomposition Solver 활용 vs 안한 경우 계산속도 비교 
    *  LU Decomposition Solver가 b를 바꿀때는 더 유리, A를 바꿀때는 큰 차이 없음

* Diagonal Pivoting Method : L,D,perm = linalg.ldl(A,lower=True,hermitian =True)
    * symmetric & complex symmetric 일때, Hermitian일때 사용가능, solver 없음




### code

In [2]:
import numpy as np
from scipy import linalg

In [7]:
# LU decomposition
A = np.array([[7,5,6,6],[1,2,2,8],[5,4,4,8],[9,5,8,7]])
lu,piv = linalg.lu_factor(A)
print(np.eye(lu.shape[0],lu.shape[1])) #diagonal = 1 
L = np.tril(lu,k=-1) + np.eye(lu.shape[0],lu.shape[1])
U = np.triu(lu)
print(piv) # [0123][3123] perm = [3120]
perm = [3,1,2,0]
print(perm)
print("L",L)
print("U",U)
np.allclose(A,(L@U)[perm,:])

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[3 1 2 3]
[3, 1, 2, 0]
L [[1.         0.         0.         0.        ]
 [0.11111111 1.         0.         0.        ]
 [0.55555556 0.84615385 1.         0.        ]
 [0.77777778 0.76923077 0.77777778 1.        ]]
U [[ 9.          5.          8.          7.        ]
 [ 0.          1.44444444  1.11111111  7.22222222]
 [ 0.          0.         -1.38461538 -2.        ]
 [ 0.          0.          0.         -3.44444444]]


True

In [8]:
# LU Decomposition Solver
A = np.array([[7,5,6,6],[1,2,2,8],[5,4,4,8],[9,5,8,7]])
b = np.ones((4,))
lu,piv = linalg.lu_factor(A)
x = linalg.lu_solve((lu,piv),b)
np.allclose(A@x,b)

True