### 학습 내용
>행렬 분해

>QR decomposition
* QR Decomposition : Q,R = linalg.qr(A,mode = "econmomic")
    * A = QR : orthogonal / unitary
    * Q,R = linalg.qr(A,mode = "economic")
        * mode 미입력시 full로 설정. 비효율적, 항상 economic을 쓰는 것 추천
    * Lapack : geqrf , orfqr / ungqr

* one - Step Approch QR 알고리즘
    * $A = Q_1R_1 \to A_1 = R_1Q_1$  # A_1 is similar to A
        * $ A_1 = Q_2R_2 \to A_2 = R_2Q_2$
        * $ A_{k-1} = Q_kR_k \to A_k = R_kQ_k$ #A_k is similar to A
        * $A_k$는 upper triangular matrix(Schur form)
            * $A_k$의 대각항 : eigenvalues

* Hessenberg Reduction : H, U = linalg.hessenberg(A, clac_q = True)
    * $A = UHU^T, A=UHU^*$
        * U : orthogonal / unitary
        * H : upper Hessenberg
        * calc_q = True : U도 함께 반환 *clac_q = True했을때 안되서 그냥 True 하니까 됨;; 이유모름
        * clac_q = False : H만 반환
    * Qr descomposition을 하면 Two-step approach QR알고리즘을 흉내낼 수 있을까? 강의 시점에서는 불가능
    
    

### code

In [1]:
import numpy as np
from scipy import linalg

In [4]:
# QR decomposition
A = np.tri(4,3,k = 0, dtype = np.float64)
Q , R = linalg.qr(A,mode = "economic")
np.allclose(A, Q@R) 

True

In [9]:
# one - Step Approch QR 알고리즘
A = np.array([[1,3,3],[-3,-5,-3],[3,3,1]],dtype= np.float64)
eigvals = linalg.eig(A)
A, eigvals

(array([[ 1.,  3.,  3.],
        [-3., -5., -3.],
        [ 3.,  3.,  1.]]),
 (array([ 1.+0.j, -2.+0.j, -2.+0.j]),
  array([[-0.57735027, -0.78762616,  0.42064462],
         [ 0.57735027,  0.20744308, -0.81636981],
         [-0.57735027,  0.58018308,  0.3957252 ]])))

In [12]:
Ak = A
for k in range(0,100) :
    Q,R = linalg.qr(Ak)
    Ak = R@Q
    print(k)
    print(Ak) # diagonal : -2 -2 1 : eigenvalues

0
[[-0.89473684 -0.94257159 -8.2171486 ]
 [ 0.33663271 -2.28708134 -2.5027171 ]
 [-0.29346959  0.25027171  0.18181818]]
1
[[-2.78947368  0.27078724  5.90167107]
 [-0.75820427 -1.73993808  5.66791813]
 [-0.47213369  0.16194052  1.52941176]]
2
[[-1.65030675 -0.23261249 -7.72147344]
 [ 0.16650157 -2.1107552  -3.67647206]
 [-0.1250441   0.0831781   0.76106195]]
3
[[-2.19290466  0.10164088  7.09228963]
 [-0.1241721  -1.9345741   4.56528391]
 [-0.08506494  0.04482046  1.12747875]]
4
[[-1.90775585 -0.05542518 -7.45732128]
 [ 0.05060771 -2.0304078  -4.09129432]
 [-0.03634394  0.02183736  0.93816365]]
5
[[-2.04723517  0.02669637  7.28948697]
 [-0.02799846 -1.98417583  4.32081471]
 [-0.01964325  0.01110197  1.031411  ]]
6
[[-1.97665475e+00 -1.36179681e-02 -7.37679133e+00]
 [ 1.33049207e-02 -2.00776115e+00 -4.20417936e+00]
 [-9.44474854e-03  5.50939816e-03  9.84415898e-01]]
7
[[-2.01174155e+00  6.74357474e-03  7.33401977e+00]
 [-6.82337974e-03 -1.99608110e+00  4.26202779e+00]
 [-4.81543461e-03  2

In [17]:
# 10 x 10 랜덤 행렬을 만들어서 Hessenberg reduction 해보기 
A = np.random.rand(10,10)
H, U = linalg.hessenberg(A,True)
print(A, H, np.allclose(A,U@H@U.T))

[[0.37330571 0.40546779 0.36946376 0.09509525 0.21897687 0.93777752
  0.08089598 0.620306   0.69168738 0.68150977]
 [0.38096353 0.07061668 0.17259214 0.3618527  0.07848483 0.86085464
  0.03185197 0.40715377 0.61419467 0.22783661]
 [0.09577019 0.83794212 0.97686674 0.72900819 0.24732284 0.60119467
  0.12930225 0.41635667 0.10623584 0.66182288]
 [0.83221202 0.14102275 0.64730311 0.02821464 0.62163604 0.64798469
  0.86239189 0.24639715 0.34082751 0.63942187]
 [0.91363814 0.67451626 0.05228845 0.61297754 0.39002107 0.63873267
  0.89248435 0.1684555  0.25479384 0.14602886]
 [0.31865311 0.95316789 0.5773761  0.40584935 0.06647728 0.80899719
  0.28123254 0.25417316 0.28455514 0.8374312 ]
 [0.20848425 0.27731028 0.05890994 0.62762248 0.91193285 0.02922312
  0.52687668 0.97515154 0.46353466 0.65933825]
 [0.41912932 0.78029313 0.14355285 0.99149524 0.40873607 0.52248399
  0.35693344 0.27516083 0.16554855 0.99253797]
 [0.32521575 0.3949093  0.87262828 0.91757313 0.12500361 0.22632551
  0.85823007

In [18]:
# 연습문제