# MultiVariable Linear Regression
* Multi varaiable : Multi feature 
* $H(x_1,x_2,x_3,....,x_n) = w_1x_1 + w_2x_2 + w_3x_3 +...+w_nx_n + b$
    * using matrix : $H(X) = XW$
    * TensorFlow : 이론적으로 사용할 때는 $H(x)=Wx+b$로 표현 하지만 텐서플로우에서는 $H(X) = XW$로 사용
    




In [2]:
import numpy as np 
import tensorflow as tf

# data
x1 = [73., 93., 89., 96., 73.]
x2 = [80., 88., 91., 98., 66.]
x3 = [75., 93., 90., 100., 70.]
# label
Y = [152., 185., 180., 196., 142.]

# random weight 
w1 = tf.Variable(tf.random.normal([1]))
w2 = tf.Variable(tf.random.normal([1]))
w3 = tf.Variable(tf.random.normal([1]))
b = tf.Variable(tf.random.normal([1]))

learning_rate = 0.000001

for i in range(1000+1) :
    # tf.GradientTape() : costfunction의 기울기등 모든 연산을 테이프에 기록하는 API 
    with tf.GradientTape() as tape :     
        hypothesis = w1*x1 + w2*x2 + w3*x3 + b
        cost = tf.reduce_mean(tf.square(hypothesis - Y))
    
    # calculates the gradients of the cost
    w1_grad, w2_grad, w3_grad, b_grad = tape.gradient(cost, [w1, w2, w3, b]) # cost를 리스트 원소별로 각각 미분한 것 
    
    # update w1, w2, w3 and b 
    w1.assign_sub(learning_rate * w1_grad)  # w1 에 learningrate*미분값 만큼빼서 업데이트 
    w2.assign_sub(learning_rate * w2_grad)
    w3.assign_sub(learning_rate * w3_grad)
    b.assign_sub(learning_rate * b_grad)
    
    if i % 50 == 0 :
        print("{:5}|{:12.4f}".format(i, cost.numpy()))

    0| 109531.6016
   50|   1216.6608
  100|     14.7920
  150|      1.4555
  200|      1.3069
  250|      1.3046
  300|      1.3040
  350|      1.3034
  400|      1.3028
  450|      1.3022
  500|      1.3016
  550|      1.3009
  600|      1.3003
  650|      1.2997
  700|      1.2991
  750|      1.2985
  800|      1.2979
  850|      1.2973
  900|      1.2967
  950|      1.2961
 1000|      1.2955


In [20]:
import numpy as np 
import tensorflow as tf
# using Matrix : Multivariable linear regression
data = np.array([
    #x1 , x2, x3, y
    [73. , 80., 75., 152.],
    [93., 88., 93., 185.],
    [89., 91., 90., 180.],
    [96., 98., 100., 196.],
    [73., 66., 70., 142.]
], dtype = np.float32)

# slice data
X = data[:, :-1] # x1,x2,x3
y = data[:,[-1]] # y 

W = tf.Variable(tf.random.normal([3,1])) # shape(3,1)로 생성
b = tf.Variable(tf.random.normal([1]))

learning_rate = 0.000001

# hypothesis, prediction function
def predict(X) :
    return tf.matmul(X,W) + b 

n_epochs = 2000
for i in range(n_epochs+1) :
    with tf.GradientTape() as tape :
        cost = tf.reduce_mean((tf.square(predict(X) - y)))
    
    W_grad, b_grad = tape.gradient(cost, [W,b])   
    #tape.gradient : 미분을 계산해줌 
    
    W.assign_sub(learning_rate * W_grad)
    b.assign_sub(learning_rate * b_grad)
    
    if i % 100 == 0 :
        print("{:5}|{:10.4f}".format(i, cost.numpy()))

    0|49057.2891
  100|   10.4687
  200|    4.4225
  300|    4.4142
  400|    4.4068
  500|    4.3994
  600|    4.3920
  700|    4.3847
  800|    4.3774
  900|    4.3701
 1000|    4.3628
 1100|    4.3556
 1200|    4.3484
 1300|    4.3413
 1400|    4.3341
 1500|    4.3270
 1600|    4.3199
 1700|    4.3129
 1800|    4.3058
 1900|    4.2989
 2000|    4.2919


In [10]:
W = tf.Variable(tf.random.normal([3,1]))

In [15]:
W

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[-0.28642625],
       [ 2.1627512 ],
       [-0.3980041 ]], dtype=float32)>

In [16]:
b

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([-2.0558567], dtype=float32)>

In [8]:
X

array([[ 73.,  80.,  75.],
       [ 93.,  88.,  93.],
       [ 89.,  91.,  90.],
       [ 96.,  98., 100.],
       [ 73.,  66.,  70.]], dtype=float32)

In [7]:
y

array([[152.],
       [185.],
       [180.],
       [196.],
       [142.]], dtype=float32)

In [5]:
predict(X)

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[205.89403],
       [240.30717],
       [240.73746],
       [257.9994 ],
       [185.10709]], dtype=float32)>