In [2]:
import torch
import torch.nn as nn

In [3]:
class Model(nn.Module):
    
    def __init__(self, num_features, hid_dim, Q):
        super().__init__()
        self.layer1 = nn.Linear(num_features, hid_dim, )
        self.layer2 = nn.Linear(hid_dim, Q)
        
    def forward(self, x):
        out = torch.tanh(self.layer1(x))
        return torch.tanh(self.layer2(out))

In [4]:
model = Model(784, 128, 5)

In [5]:
bsz = 32
pred = model(torch.randn(32, 784))

In [6]:
pred[0]

tensor([ 0.0908, -0.4472, -0.3893,  0.0318, -0.1661], grad_fn=<SelectBackward>)

In [7]:
target = torch.LongTensor(32, 5).random_(2)
target[target == 0] = -1

In [8]:
target[0]

tensor([ 1,  1,  1, -1, -1])

In [9]:
x = torch.LongTensor(32, 5).random_(10)

In [10]:
(target == 1).size()

torch.Size([32, 5])

In [11]:
pred[0]

tensor([ 0.0908, -0.4472, -0.3893,  0.0318, -0.1661], grad_fn=<SelectBackward>)

In [12]:
target[0]

tensor([ 1,  1,  1, -1, -1])

In [13]:
Y = pred[0][target[0] == 1]
Y

tensor([ 0.0908, -0.4472, -0.3893], grad_fn=<IndexBackward>)

In [14]:
Y_bar = pred[0][target[0] != 1]
Y_bar

tensor([ 0.0318, -0.1661], grad_fn=<IndexBackward>)

In [16]:
import numpy as np

In [31]:
torch.cartesian_prod(Y, Y_bar)

tensor([[ 0.0908,  0.0318],
        [ 0.0908, -0.1661],
        [-0.4472,  0.0318],
        [-0.4472, -0.1661],
        [-0.3893,  0.0318],
        [-0.3893, -0.1661]], grad_fn=<StackBackward>)

6

In [39]:
sum(torch.exp(torch.cartesian_prod(Y, -Y_bar).sum(dim=-1)))/ len(torch.cartesian_prod(Y, Y_bar))

tensor(0.8640, grad_fn=<DivBackward0>)

In [40]:
target

tensor([[ 1,  1,  1, -1, -1],
        [-1,  1, -1, -1,  1],
        [ 1, -1,  1,  1, -1],
        [-1, -1,  1, -1,  1],
        [-1, -1,  1,  1,  1],
        [ 1,  1, -1, -1,  1],
        [-1,  1, -1,  1,  1],
        [-1, -1,  1,  1,  1],
        [-1, -1,  1,  1, -1],
        [-1,  1, -1,  1,  1],
        [ 1,  1, -1, -1, -1],
        [-1, -1,  1,  1,  1],
        [-1,  1,  1, -1,  1],
        [ 1, -1,  1, -1,  1],
        [ 1,  1, -1,  1, -1],
        [ 1, -1, -1, -1,  1],
        [-1, -1,  1,  1, -1],
        [-1, -1,  1, -1, -1],
        [-1, -1, -1, -1,  1],
        [ 1,  1,  1,  1, -1],
        [-1,  1, -1, -1, -1],
        [ 1, -1,  1, -1,  1],
        [-1,  1, -1,  1,  1],
        [ 1,  1, -1,  1,  1],
        [ 1, -1,  1,  1,  1],
        [ 1,  1,  1, -1,  1],
        [-1, -1,  1,  1,  1],
        [-1,  1,  1, -1,  1],
        [ 1, -1, -1,  1,  1],
        [-1,  1,  1,  1, -1],
        [-1, -1, -1,  1, -1],
        [-1,  1,  1, -1, -1]])

In [43]:
len(target)

32

In [49]:
pred = model(torch.randn(32, 784))

In [60]:
target = torch.LongTensor(32, 5).random_(2)
target[target == 0] = -1

# division zero 해결을 위한 전처리 offset
target[:, -2] = 1
target[:, -1] = -1

In [48]:
# BP_MLL loss 
loss_sum = 0
for i in range(len(target)) : 
    Y = pred[i][target[i] == 1]
    Y_bar = pred[i][target[i] != 1]
    loss = sum(torch.exp(torch.cartesian_prod(Y, -Y_bar).sum(dim=-1)))/ len(torch.cartesian_prod(Y, Y_bar))
    loss_sum += loss
    print(loss)
print('loss : ',loss_sum)

tensor(0.8640, grad_fn=<DivBackward0>)
tensor(1.0888, grad_fn=<DivBackward0>)
tensor(0.6826, grad_fn=<DivBackward0>)
tensor(0.8377, grad_fn=<DivBackward0>)
tensor(1.5775, grad_fn=<DivBackward0>)
tensor(1.0015, grad_fn=<DivBackward0>)
tensor(1.2708, grad_fn=<DivBackward0>)
tensor(0.6839, grad_fn=<DivBackward0>)
tensor(1.0860, grad_fn=<DivBackward0>)
tensor(0.7861, grad_fn=<DivBackward0>)
tensor(0.9061, grad_fn=<DivBackward0>)
tensor(1.0976, grad_fn=<DivBackward0>)
tensor(0.7878, grad_fn=<DivBackward0>)
tensor(1.4885, grad_fn=<DivBackward0>)
tensor(1.0190, grad_fn=<DivBackward0>)
tensor(0.9869, grad_fn=<DivBackward0>)
tensor(1.5468, grad_fn=<DivBackward0>)
tensor(0.7161, grad_fn=<DivBackward0>)
tensor(0.6136, grad_fn=<DivBackward0>)
tensor(0.9594, grad_fn=<DivBackward0>)
tensor(0.7292, grad_fn=<DivBackward0>)
tensor(0.8682, grad_fn=<DivBackward0>)
tensor(1.0440, grad_fn=<DivBackward0>)
tensor(0.9366, grad_fn=<DivBackward0>)
tensor(1.5584, grad_fn=<DivBackward0>)
tensor(0.8680, grad_fn=<D

In [61]:
class BPMLLLoss(nn.Module):

    def __init__(self, size_average=None, reduce=None, reduction='mean'):
        super().__init__()
        if size_average is not None or reduce is not None:
            self.reduction = _Reduction.legacy_get_string(size_average, reduce)
        else:
            self.reduction = reduction

    def forward(self, input, target):
        # https://cs.nju.edu.cn/zhouzh/zhouzh.files/publication/tkde06a.pdf
        # input's shape is (bsz, Q)
        # target's shape is (bsz, Q)
        # target's unique value is in [-1, 1]
        # 
        loss_sum = 0
        for i in range(len(target)) : 
            Y = input[i][target[i] == 1]
            Y_bar = input[i][target[i] != 1]
            loss = sum(torch.exp(-torch.cartesian_prod(Y, -Y_bar).sum(dim=-1)))/ len(torch.cartesian_prod(Y, Y_bar))
            loss_sum += loss
        return loss_sum
        

In [62]:
criterion = BPMLLLoss()

In [63]:
criterion(pred, target)

tensor(33.1967, grad_fn=<AddBackward0>)